Added solutions for tasks #MeetupView-script-setup, #MeetupCover-style-v-bind, #UiStretch
js-tasks-ru/vue-20240924_roman803 pull request #6
Opened 2024-10-28 18:07 UTC by rmirskov

Added solutions for tasks #MeetupView-script-setup, #MeetupCover-style-v-bind, #UiStretch

2024-10-28 18:07 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-11-25 22:58 UTC, ShGKme requested changes
Добрый вечер. Понимаю, что может быть тяжело вносить правки после большого перерыва, но требуется исправления.

В целом всё отлично, но в последней задаче некорректно используется `v-bind` в CSS

2024-11-25 22:58 UTC, ShGKme commented on 04-sfc/20-MeetupCover-style-v-bind/MeetupCover.vue
> +  background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), var(v-bind(bgStyle), var(--default-cover));
`v-bind(bgStyle)` - заменится на получение значения CSS переменной через `var()`. Здесь это не будет работать по трём причинам:
1. Объект `{ '--bg-url': `url('${props.image}')` }` не может быть значением `background-image`
2. Фон не может использоваться как значение CSS переменной (второго `var()`)
3. Даже если бы это работало, при значении `undefined` это всё равно было бы значением (строкой) и значение по умолчканию `var(--default-cover)` не будет принято

Требуется вычислить некое новое свойство в компоненте, значением которого будет непосредственно фон. Либо `url()`, либо `var(--default-cover)`

2024-11-26 05:53 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-11-26 05:58 UTC, rmirskov commented
Здравствуйте! Спасибо за обратную связь! По поводу 2 пункта я нашел другое мнение https://developer.mozilla.org/en-US/docs/Web/CSS/var#using_a_custom_property_as_a_fallback. Хотя допускаю, что со свойством background-image дело обстоит именно так, как указано в Вашем комментарии.

2024-11-26 15:37 UTC, ShGKme commented
> По поводу 2 пункта я нашел другое мнение https://developer.mozilla.org/en-US/docs/Web/CSS/var#using_a_custom_property_as_a_fallback.

`var` поддерживает fallback значение. Но `v-bind()` здесь заменится на существующую переменную с `undefined` значением. Её значение будет строкой.

1. `var(v-bind(bgStyle), var(--default-cover))` компилируется в `var(var(--bgStyle), var(--default-cover))`
2. Переменная определена как `--bgStyle: undefined`
3. Что работает как `var(undefined, var(--default-cover))`

`undefined` для CSS не отсутствие переменной, а буквально значение `undefined` (не валидное, но значение). Переменная есть, и в fallback не уходит

[Пример](https://play.vuejs.org/#eNp9UctuwjAQ/BXLF0DiIdSeaEBqKw7toa0KR1+CswkGx7bsTUqF8u9dm0I5VJySnRnPzthH/ujcuG2Az3gWpFcOWQBs3EIYVTvrkR2Zh5J1rPS2Zj2S9oQRRloTkG2qFX5rYPOo6TemgFIZKAbCZJOTG/nQgFA7nSPQxFi2nTKp8xDmgiMEFHyxpk822U6JzyZXYhpDWhCkdVAQMo4n2DH6bHK5r7ylrSNptfUz1ua+3442yhT932SDISUrBg/CdClTxMiFDzmSpSlVNd4Fa6h9shRc2topDf7doaKKgs9OyyKXa22/XhOGvoHhGZdbkPt/8F04REzwDw8BfAuCXzjMfQVUPdLL1Rsc6P9C1rZoNKlvkJ8QrG5ixpPsia6BYl/pUtqX9IbKVOuwPCCYcC4Vg0Zll/SC07s+36j+F/dufJ/O0Y3y7ge0eMGi)

2024-11-26 15:37 UTC, ShGKme approved these changes
Принято

2024-11-26 15:38 UTC, merged